/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-06 01:16:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.theater;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import member.model.vo.Member;

public final class theaterInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578022508000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577923558000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write('\n');
      out.write('\n');

	//로그인한 경우
	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	//System.out.println("memberLoggedIn@header.jsp="+memberLoggedIn);

	//쿠키관련
	boolean saveId = false;
	String loginId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();
			
			if("saveId".equals(k)) {
				saveId = true;
				loginId = v;
			}
		}
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>PIXARBOX</title>\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("<!--웹폰트추가  -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Anton|Do+Hyeon|Nanum+Gothic+Coding&display=swap&subset=latin-ext,vietnamese\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script> -->\n");
      out.write("\n");
      out.write("<!--슬라이드코드추가--> \n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 파비콘추가-->\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 헤더  -->\n");
      out.write("<header id=\"header\" class=\"header_main\">\n");
      out.write("\n");
      out.write("<!-- 두번째 헤더 -->\n");
      out.write("    <div class=\"sec_haed\">\n");
      out.write("\t    <!-- 고정헤더 -->\n");
      out.write("\t    <nav id=\"topUtil\" class=\"top_util\">\n");
      out.write("\t        <span>PIXAR</span>\n");
      out.write("\t        <ul class=\"nav\">\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 if(memberLoggedIn == null) { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogin\" id=\"login_btn\">로그인</a>        \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=\"sign_btn\">회원가입</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 }
	        else if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())) { 
	        
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t        \t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\" id=\"admin_btn\">관리자페이지</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a></li>\n");
      out.write("\t        ");
 }
	        else { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"mypage_btn\">마이페이지</a>   \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t    ");
 } 
      out.write("\n");
      out.write("\t        </ul>\n");
      out.write("\t    </nav>\n");
      out.write("\t<!-- 고정헤더 끝 -->\n");
      out.write("        <nav id=\"secUtil\" class=\"sec_util\">\n");
      out.write("            \n");
      out.write("            <span>\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">PIXAR<br><br>BOX</a>\n");
      out.write("            </span>\n");
      out.write("                \n");
      out.write("            <ul class=\"nav-sec\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/ticket/ticketingStep1/step1.do\">예매</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/movie/boxOffice/order1.do\">영화</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/theater/theaterInfo\">영화관</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">이벤트</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">스토어</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">VOD</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </div><!--div.sec_haed-->\n");
      out.write("    <!-- 두번째 헤더 끝 -->\n");
      out.write("</header>\n");
      out.write("<!-- 헤더 끝 -->\n");
      out.write("\n");
      out.write("<!-- <section id=\"content\"> -->\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/theater.css\" />\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- ! 할 일  ! -->\n");
      out.write("<!--\n");
      out.write("[jsp] \n");
      out.write("- 요일 표시?\n");
      out.write("- 심야 표시\n");
      out.write("- 8일/11일 시간표 없음 표시\n");
      out.write("-  ★이미지 클릭 잘 안 먹음\n");
      out.write("\n");
      out.write("[css]\n");
      out.write("- 호버 시 색상 영역\n");
      out.write("- css => 가운데로\n");
      out.write("\n");
      out.write("\n");
      out.write(" -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("var date;\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("$(()=>{\n");
      out.write("\t/* showList_9(); */\n");
      out.write("\tdate = 10;\n");
      out.write("\tshowList_9(date);\n");
      out.write("\t\n");
      out.write("\t$(\"#btn-right\").click(function(){\n");
      out.write("\t\tconsole.log(\"date=\"+date);\n");
      out.write("\t\tif(date < 12){\n");
      out.write("\t\t\tshowList_9(++date);\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$(\"#btn-left\").click(function(){\n");
      out.write("\t\tconsole.log(\"date=\"+date);\n");
      out.write("\t\tif(date > 10){\n");
      out.write("\t\t\tshowList_9(--date);\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("});\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("var srch_date;\n");
      out.write("var cnt = 1;\n");
      out.write("\n");
      out.write("//9일\n");
      out.write("function showList_9(d){\n");
      out.write("\n");
      out.write("\t\tif(d == 10){\n");
      out.write("\t\t\tsrch_date = '2020-01-10';\t\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(d == 11){\n");
      out.write("\t\t\tsrch_date = '2020-01-11';\n");
      out.write("\t\t}\n");
      out.write("\t\telse if (d == 12){\n");
      out.write("\t\t\tsrch_date = '2020-01-12';\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t$.ajax({\n");
      out.write("\t\t\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/theater/srchTheaterInfo\",\n");
      out.write("\t\t/* data: {srchDate: '2020-01-09'}, */\n");
      out.write("\t\tdata: {srchDate: srch_date},\t\t\n");
      out.write("\t\ttype: \"get\",\n");
      out.write("\t\tdataType: \"json\",\n");
      out.write("\t\tsuccess: data => {\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tlet $tr;\n");
      out.write("\t\t\tlet $date = $(\"#date\");\t\n");
      out.write("\t\t\tlet $day = $(\"#day\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfor(let i in data){\n");
      out.write("\t\t\t\tlet s = data[i];\n");
      out.write("\t\t\t\tconsole.log(s);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif(i == 1) {\n");
      out.write("\t\t\t\t\t\n");
      out.write(" \t\t\t\t\tvar dateArr = (s.showDate).split('-');\n");
      out.write(" \t\t\t\t\tconsole.log(dateArr[1]);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$date.html(dateArr[1]+\".\"+dateArr[2]);\n");
      out.write("\t\t\t\t\t/* 초기화해줘야 함!!! */\n");
      out.write("\t\t\t\t\t$(\"#schedule\").html(\"\");\n");
      out.write("\t\t\t\t\t/* $day.append(dateArr[3]); */\n");
      out.write("\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write(" \t\t\t\t//결과1: 영화명마다\n");
      out.write(" \t\t\t\tif(s.showTurn == 1){\n");
      out.write("\t\t\t\t\t$tr = $(\"<tr></tr>\");\n");
      out.write("\t\t\t\t\tlet html = \"<td rowspan='1' class='movie-title'>\"+s.movieTitle+\"</td>\";\n");
      out.write("\t\t\t\t\thtml += \"<td rowspan='1' class='movie-theater'>\"+s.screenCode+\"관<br>디지털(자막)</td>\";\n");
      out.write("\t\t            html += \"<td><div class='reservation'>\";\n");
      out.write("\t\t            html += \"<p>\"+s.startTime+\" ~ \"+s.endTime+\"</p><br>\";\n");
      out.write("\t  \t\t        html += \"<a href='javascript:void(0);' onclick='ticketingGo(\"+s.showCode+\",\"+s.showTurn+\");'>빠른예매</a></div>\";\n");
      out.write("\t\t            html += \"<p class='jojo' style='font-weight: bold; color: #35256b; font-size: 17px;'>조조</p><br>\"; \n");
      out.write("\t\t            html += \"<p class='time'>\"+s.startTime+\"</p><br>\"; \n");
      out.write("\t\t            html += \"<p class='seat'>\"+s.remainSeats+\"/\"+s.seatCnt+\"</p></td>\";\t\t            \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t            $tr.append(html);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif(s.showTurn != 1) {\n");
      out.write("\t\t            let html = \"<td><div class='reservation'>\";\n");
      out.write("\t\t            html += \"<p>\"+s.startTime+\" ~ \"+s.endTime+\"</p><br>\";\n");
      out.write(" \t  \t\t        html += \"<a href='javascript:void(0);' onclick='ticketingGo(\"+s.showCode+\",\"+s.showTurn+\");'>빠른예매</a></div>\";\n");
      out.write("\t\t            html += \"<p class='jojo'></p><br>\"; \n");
      out.write("\t\t            html += \"<p class='time'>\"+s.startTime+\"</p><br>\"; \n");
      out.write("\t\t            html += \"<p class='seat'>\"+s.remainSeats+\"/\"+s.seatCnt+\"</p></td>\";\t\n");
      out.write("\t\t               \n");
      out.write("\t\t\t\t\t$tr.append(html);\n");
      out.write("\t\t\t\t}  \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(\"#schedule\").append($tr);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t},\n");
      out.write("\t\terror : (jqxhr, textStatus, errorThrown)=>{\n");
      out.write("\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("function ticketingGo(showCode, showTurn){\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write(" \tif(");
      out.print(memberLoggedIn==null);
      out.write("){\t\t\n");
      out.write(" \t\talert(\"로그인 후 이용하실 수 있습니다.\");\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLogin\";\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/ticket/ticketingStep2/step2.do?showCode=\"+showCode;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <section>\n");
      out.write("\t<div id=\"div-introduction\">\n");
      out.write("\t\t<h1>PIXAR BOX</h1>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<p>강남역과 역삼역 사이에 있는 젊은이들의</p><p class=\"highlight\">&nbsp;Hot Place!</p><br />\n");
      out.write("\t\t\t<p>최고의 사운드의 최상의 공간을 자랑하는</p><p class=\"highlight\">&nbsp;PIXAR BOX!</p><br />\n");
      out.write("\t\t\t<p>Pixar Animation Studios의 장편영화만을 상영하는</p><br />\n");
      out.write("\t\t\t<p>Pixar Animation 전용 상영관에 오신 걸 환영합니다.</p><br />\n");
      out.write("\t\t    <p class=\"highlight\">5관/369석</p>\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/theaterImage.png\" alt=\"\" id=\"img-theaterInfo\"/>\t\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"menu\">\n");
      out.write("        <a href=\"#1\">상영시간표</a>\n");
      out.write("        <a href=\"#2\">위치/교통</a>\n");
      out.write("        <a href=\"#3\">관람료</a>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"1\"></div>\n");
      out.write("    <br /><br><br>\n");
      out.write("    \n");
      out.write("    <div id=\"div-scheduleOfShow\">\n");
      out.write("\t    <h2 class=\"title\">상영시간표</h2>\n");
      out.write("\t    \n");
      out.write("\t    <div id=\"div-date\">\n");
      out.write("\t    \t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/left.png\" id=\"btn-left\" style=\"cursor: pointer;\"/>\n");
      out.write("\t        <p id=\"date\"></p>\n");
      out.write("\t        <p id=\"day\"></p>\n");
      out.write("\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/right.png\" alt=\"\" id=\"btn-right\" style=\"cursor: pointer;\"/>\n");
      out.write("\t        <div id=\"ratingInfo\">\n");
      out.write("\t\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/ratingInfo.png\" alt=\"\" id=\"img-ratingInfo\"/>\n");
      out.write("\t\t        <input type=\"button\" value=\"관람등급 안내\" onclick=\"ratings();\" id=\"btn-ratings\" style=\"cursor: pointer;\"/>\t        \n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t\t<!-- 상영리스트 -->\n");
      out.write("\t\t<table id=schedule></table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("   \n");
      out.write("    <div id=\"2\"></div>\n");
      out.write("   \t<br /><br><br>\n");
      out.write("   \t\n");
      out.write("\t<div id=\"div-location\">\n");
      out.write("\t\t<h2 class=\"title\">위치/교통</h2>\n");
      out.write("\t\t    <!-- <div id=\"map\"> -->\n");
      out.write("\t\t    \t<!-- * 카카오맵 - 지도퍼가기 -->\n");
      out.write("\t\t\t\t<!-- 1. 지도 노드 -->\n");
      out.write("\t\t\t\t<div id=\"daumRoughmapContainer1576223876110\" class=\"root_daum_roughmap root_daum_roughmap_landing\"></div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t<!--2. 설치 스크립트\n");
      out.write("\t\t\t\t* 지도 퍼가기 서비스를 2개 이상 넣을 경우, 설치 스크립트는 하나만 삽입합니다.-->\n");
      out.write("\t\t\t\t<script charset=\"UTF-8\" class=\"daum_roughmap_loader_script\" src=\"https://ssl.daumcdn.net/dmaps/map_js_init/roughmapLoader.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t<!-- 3. 실행 스크립트 -->\n");
      out.write("\t\t\t\t<script charset=\"UTF-8\">\n");
      out.write("\t\t\t\tnew daum.roughmap.Lander({\n");
      out.write("\t\t\t\t\t\"timestamp\" : \"1576223876110\",\n");
      out.write("\t\t\t\t\t\"key\" : \"w8wc\",\n");
      out.write("\t\t\t\t\t\"mapWidth\" : \"500\",\n");
      out.write("\t\t\t\t\t\"mapHeight\" : \"360\"\n");
      out.write("\t\t\t\t}).render();\n");
      out.write("\t\t\t\t</script>\n");
      out.write("\t\t   <!--  </div> -->\n");
      out.write("\t\t    <div id=\"mapInfo\">\n");
      out.write("\t\t    \t<div id=\"subwayInfo\">\n");
      out.write("\t\t    \t<table id=\"maptable\">\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t    \t\t\t<td>\n");
      out.write("\t\t    \t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/subway.png\" id=\"subway\" alt=\"\" />\n");
      out.write("\t\t    \t\t\t</td>\n");
      out.write("\t\t    \t\t\t<td>\n");
      out.write("\t\t    \t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/line2.png\" alt=\"\"  id=\"line2\"/>\n");
      out.write("\t\t\t\t   \t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/lineNew.png\" alt=\"\" id=\"lineNew\"/>\n");
      out.write("\t\t    \t\t\t</td>\n");
      out.write("\t\t    \t\t\t<td><p>강남역 1번출구</p></td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t    \t\t\t<td\tid=\"subwayTitle\"><p>지하철</p></td>\n");
      out.write("\t\t    \t\t\t<td>\n");
      out.write("\t\t    \t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/line2.png\" alt=\"\"  id=\"line2\"/>\n");
      out.write("\t\t    \t\t\t</td>\n");
      out.write("\t\t    \t\t\t<td><p>역삼역 3번출구</p></td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t    \t</table>\n");
      out.write("\t\t    \t</div>\n");
      out.write("\t\t    \t<div>\n");
      out.write("\t\t    \t<table id=\"maptable\">\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t    \t\t\t<td rowspan=\"2\">\n");
      out.write("\t\t    \t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/bus.png\" id=\"bus\" alt=\"\" />\n");
      out.write("\t\t    \t\t\t</td>\n");
      out.write("\t\t    \t\t\t<td id=\"first\">\n");
      out.write("\t\t    \t\t\t\t<p>역삼역, 포스코타워역삼(23-288)</p>\n");
      out.write("\t\t    \t\t\t</td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t    \t\t<tr><td><p>강남역(23-813)</p></td></tr>\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t    \t\t\t<td id=\"busTitle\"><p>버스</p></td>\n");
      out.write("\t\t    \t\t\t<td>강남역 12번출구(23-814)</td>\n");
      out.write("\t\t    \t\t</tr>\n");
      out.write("\t\t    \t</table>\n");
      out.write("\t\t    \t</div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t</div>\n");
      out.write("   \t\n");
      out.write("    <div id=\"3\"></div>\n");
      out.write("    <div id=\"div-price\">\n");
      out.write("\t\t<h2 class=\"title\">관람료</h2>\n");
      out.write("\t    <table id=price>\n");
      out.write("\t        <tr><th>상영시간</th>\n");
      out.write("\t            <th>성인</th>\n");
      out.write("\t            <th>청소년</th>\n");
      out.write("\t            <th>경로<br>(만 65세이상)</th>\n");
      out.write("\t            <th>미취학 아동<br>(만 4세~ 만 6세)</th>\n");
      out.write("\t        </tr>\n");
      out.write("\t        <tr><td>조조(첫 회차)</td>\n");
      out.write("\t            <td>7,000</td>\n");
      out.write("\t            <td>6,000</td>\n");
      out.write("\t            <td>5,000</td>\n");
      out.write("\t            <td>5,000</td>\n");
      out.write("\t        </tr>\n");
      out.write("\t        <tr><td>일반(2회차 ~ 24시 전)</td>\n");
      out.write("\t            <td>11,000</td>\n");
      out.write("\t            <td>9,000</td>\n");
      out.write("\t            <td>5,000</td>\n");
      out.write("\t            <td>5,000</td>\n");
      out.write("\t        </tr>\n");
      out.write("\t<!--         <tr><td>심야(24시~)</td>\n");
      out.write("\t            <td>9,000</td>\n");
      out.write("\t            <td>7,000</td>\n");
      out.write("\t            <td>5,000</td>\n");
      out.write("\t            <td>5,000</td>\n");
      out.write("\t        </tr> -->\n");
      out.write("\t        \n");
      out.write("\t    </table>\n");
      out.write("    \n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("function ratings(){\n");
      out.write("\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/theater/movieRatings\";\n");
      out.write("\tvar title=\"관람등급 안내\";\n");
      out.write("\tvar spec=\"left=500px, top=200px, width=650px, height=350px\";\n");
      out.write("\topen(url, title, spec);\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\"> -->\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!-- 풋터 -->\n");
      out.write("<footer class=\"foot\">\n");
      out.write("    <div id=bottomFoot class=\"bottom_foot\">\n");
      out.write("        <ul class=\"div-bottomfoot\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">공지사항\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">고객센터\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이용약관\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이벤트\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">스토어바로가기\n");
      out.write("            </li>\n");
      out.write("        </ul>           \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- 풋터 안 인포메이션 -->\n");
      out.write("    <div id=\"infoFoot\" class=\"info_foot\">\n");
      out.write("                                \n");
      out.write("        <span>사업자정보확인</span> <span>개인정보관리자</span><span>통신판매 신고번호 제 00000123123호</span> <br><br>\n");
      out.write("        <span>대표이사: NONAME</span> <span>본점: 서울특별시 서초구 서초동 123-456</span> <span>사업장: 서울특별시 마포구 상암로 123 상암동 456</span><br><br>\n");
      out.write("        <span>고객센터: 1234-5678</span> <span>NOTITLE문의: 02-1234-5678</span> <span>NOTITLE문의:  csnotitle@notitle.com</span>\n");
      out.write("        \n");
      out.write("    <h3>PIXARBOX</h3>\n");
      out.write("    </div><!-- div.info_foot div-->\n");
      out.write("\n");
      out.write("    <div class=\"end_foot\">\n");
      out.write("        InsideOut\n");
      out.write("    </div><!--div.end_foot-->\n");
      out.write("    <!-- 풋터 안 인포메이션 끝 -->\n");
      out.write("</footer>\n");
      out.write("    <!-- 풋터 끝 -->   \n");
      out.write("            \n");
      out.write("            \n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
