/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-06 00:27:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class memberLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578022508000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577923558000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	//로그인한 경우
	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	//System.out.println("memberLoggedIn@header.jsp="+memberLoggedIn);

	//쿠키관련
	boolean saveId = false;
	String loginId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();
			
			if("saveId".equals(k)) {
				saveId = true;
				loginId = v;
			}
		}
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>PIXARBOX</title>\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("<!--웹폰트추가  -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Anton|Do+Hyeon|Nanum+Gothic+Coding&display=swap&subset=latin-ext,vietnamese\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script> -->\n");
      out.write("\n");
      out.write("<!--슬라이드코드추가--> \n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 파비콘추가-->\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 헤더  -->\n");
      out.write("<header id=\"header\" class=\"header_main\">\n");
      out.write("\n");
      out.write("<!-- 두번째 헤더 -->\n");
      out.write("    <div class=\"sec_haed\">\n");
      out.write("\t    <!-- 고정헤더 -->\n");
      out.write("\t    <nav id=\"topUtil\" class=\"top_util\">\n");
      out.write("\t        <span>PIXAR</span>\n");
      out.write("\t        <ul class=\"nav\">\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 if(memberLoggedIn == null) { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogin\" id=\"login_btn\">로그인</a>        \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=\"sign_btn\">회원가입</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 }
	        else if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())) { 
	        
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t        \t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\" id=\"admin_btn\">관리자페이지</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a></li>\n");
      out.write("\t        ");
 }
	        else { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"mypage_btn\">마이페이지</a>   \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t    ");
 } 
      out.write("\n");
      out.write("\t        </ul>\n");
      out.write("\t    </nav>\n");
      out.write("\t<!-- 고정헤더 끝 -->\n");
      out.write("        <nav id=\"secUtil\" class=\"sec_util\">\n");
      out.write("            \n");
      out.write("            <span>\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">PIXAR<br><br>BOX</a>\n");
      out.write("            </span>\n");
      out.write("                \n");
      out.write("            <ul class=\"nav-sec\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/ticket/ticketingStep1/step1.do\">예매</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/movie/boxOffice/order1.do\">영화</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/theater/theaterInfo\">영화관</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">이벤트</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">스토어</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">VOD</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </div><!--div.sec_haed-->\n");
      out.write("    <!-- 두번째 헤더 끝 -->\n");
      out.write("</header>\n");
      out.write("<!-- 헤더 끝 -->\n");
      out.write("\n");
      out.write("<!-- <section id=\"content\"> -->\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/member.css\" />\n");
      out.write("\t<script>\n");
      out.write("\tfunction loginValidate() {\n");
      out.write("\t\tvar $loginId = $(\"#loginId\");\n");
      out.write("\t\tvar $loginPwd = $(\"#loginPwd\");\n");
      out.write("\t\t\n");
      out.write("\t\tif($loginId.val().trim().length == 0) {\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\n");
      out.write("\t\t\t$loginId.focus();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tif($loginPwd.val().trim().length == 0) {\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요.\");\n");
      out.write("\t\t\t$loginPwd.focus();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\treturn true;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction goMemberEnroll() {\n");
      out.write("\t\tlocation.href = \"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\";\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t</script>\n");
      out.write("<section id=\"content-member\">\n");
      out.write("\t<h2>로그인</h2>\n");
      out.write("\t<div class=\"title\">\n");
      out.write("\t\t<hr>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"loginFrm\">\n");
      out.write("\t    <form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLoginCheck\" id=\"loginForm\" method=\"post\" onsubmit=\"return loginValidate();\">\n");
      out.write("\t        <table>\n");
      out.write("\t            <tr>\n");
      out.write("\t                <td>\n");
      out.write("\t                    <input type=\"text\" name=\"loginId\" id=\"loginId\" placeholder=\"아이디를 입력하세요.\" value=\"");
      out.print(saveId?loginId:"" );
      out.write("\">\n");
      out.write("\t                </td>\n");
      out.write("\t                <td rowspan=\"2\">\n");
      out.write("\t                    <input type=\"submit\" class=\"button login\" value=\"로그인\" tabindex=\"3\" />\n");
      out.write("\t                    <input type=\"button\" class=\"button enroll\" value=\"회원가입\" onclick=\"goMemberEnroll();\" />\n");
      out.write("\t                </td>\n");
      out.write("\t            </tr>\n");
      out.write("\t            <tr>\n");
      out.write("\t                <td>\n");
      out.write("\t                    <input type=\"password\" name=\"loginPwd\" id=\"loginPwd\" placeholder=\"비밀번호를 입력하세요.\">\n");
      out.write("\t                </td>\n");
      out.write("\t            </tr>\n");
      out.write("\t            <tr>\n");
      out.write("\t            \t<td colspan=\"2\">\n");
      out.write("\t            \t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print(saveId?"checked":"" );
      out.write(" />\n");
      out.write("\t            \t\t<label for=\"saveId\">아이디 저장</label>\n");
      out.write("\t            \t</td>\n");
      out.write("\t            </tr>\n");
      out.write("\t        </table>\n");
      out.write("\t    </form>\n");
      out.write("\t</div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\"> -->\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!-- 풋터 -->\n");
      out.write("<footer class=\"foot\">\n");
      out.write("    <div id=bottomFoot class=\"bottom_foot\">\n");
      out.write("        <ul class=\"div-bottomfoot\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">공지사항\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">고객센터\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이용약관\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이벤트\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">스토어바로가기\n");
      out.write("            </li>\n");
      out.write("        </ul>           \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- 풋터 안 인포메이션 -->\n");
      out.write("    <div id=\"infoFoot\" class=\"info_foot\">\n");
      out.write("                                \n");
      out.write("        <span>사업자정보확인</span> <span>개인정보관리자</span><span>통신판매 신고번호 제 00000123123호</span> <br><br>\n");
      out.write("        <span>대표이사: NONAME</span> <span>본점: 서울특별시 서초구 서초동 123-456</span> <span>사업장: 서울특별시 마포구 상암로 123 상암동 456</span><br><br>\n");
      out.write("        <span>고객센터: 1234-5678</span> <span>NOTITLE문의: 02-1234-5678</span> <span>NOTITLE문의:  csnotitle@notitle.com</span>\n");
      out.write("        \n");
      out.write("    <h3>PIXARBOX</h3>\n");
      out.write("    </div><!-- div.info_foot div-->\n");
      out.write("\n");
      out.write("    <div class=\"end_foot\">\n");
      out.write("        InsideOut\n");
      out.write("    </div><!--div.end_foot-->\n");
      out.write("    <!-- 풋터 안 인포메이션 끝 -->\n");
      out.write("</footer>\n");
      out.write("    <!-- 풋터 끝 -->   \n");
      out.write("            \n");
      out.write("            \n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
