/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-06 00:30:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class memberTicketingList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577923558000L));
    _jspx_dependants.put("/WEB-INF/views/common/mypageHeader.jsp", Long.valueOf(1578160788000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	//로그인한 경우
	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	
	//쿠키관련
	boolean saveId = false;
	String loginId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();
			
			if("saveId".equals(k)) {
				saveId = true;
				loginId = v;
			}
		}
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>PIXARBOX</title>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<!--웹폰트추가  -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Anton|Do+Hyeon|Nanum+Gothic+Coding&display=swap&subset=latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 두번째 헤더 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 고정헤더 -->\r\n");
      out.write("\t    <nav id=\"topUtil\" class=\"top_util\">\r\n");
      out.write("\t        <span>PIXAR</span>\r\n");
      out.write("\t        <ul class=\"nav\">\r\n");
      out.write("\t        ");
 if(memberLoggedIn == null) { 
      out.write("\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogin\" id=\"login_btn\">로그인</a>        \r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=\"sign_btn\">회원가입</a>   \r\n");
      out.write("\t\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t        ");
 }
	        else { 
      out.write("\r\n");
      out.write("\t        \t<li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \r\n");
      out.write("\t\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a>   \r\n");
      out.write("\t\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"mypage_btn\">마이페이지</a>   \r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t    ");
 } 
      out.write("\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 기본 헤더와 다른 마이페이지 부분 -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section-mypage-top\">\r\n");
      out.write("\t\t<div class=\"mypage-top-left\">\r\n");
      out.write("\t\t\t<strong class=\"mypage-id\" id=\"nickname\">");
      out.print(memberLoggedIn.getLastName()+memberLoggedIn.getFirstName() );
      out.write(" <span>님</span>\r\n");
      out.write("\t\t\t</strong>\r\n");
      out.write("\t\t\t<div class=\"mypoint\">\r\n");
      out.write("\t\t\t\t<span>포인트</span>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>");
      out.print(memberLoggedIn.getPoint() );
      out.write("</strong>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 헤더 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"tab_type01\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" id=\"pointList\">포인트내역</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/like.do?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" id=\"likeList\">찜</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/purchase.do?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" id=\"ticketingList\">예매내역</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/update.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"modifyMemberInfo\">개인정보수정</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write('\r');
      out.write('\n');

	Member m = (Member)request.getAttribute("member");

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/mypage.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/customerService.css\" />\r\n");
      out.write("<style>\r\n");
      out.write(".cancelList{color: gray;}\r\n");
      out.write(".reservationList{color: rgb(98, 80, 211);}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<section id=\"content-ticketing\">\r\n");
      out.write("<div class=\"sub-contents-wrap inner-wrap\">\r\n");
      out.write("\r\n");
      out.write(" \t\t<div class=\"tab_type02\" style=\"margin-top: 40px; margin-left: 83px;\">\r\n");
      out.write("\t\t    <ul>\r\n");
      out.write("\t\t        <li><a href=\"avascript:void(0)\" class=\"reservationList\" style=\"font-weight: bold;\">예매내역</a></li>\r\n");
      out.write("\t\t        <span>|</span>\r\n");
      out.write("\t\t        <li><a href=\"avascript:void(0)\" class=\"cancelList\" style=\"font-weight: bold;\">취소내역</a></li>\r\n");
      out.write("\t\t    </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"tbl_div\">\r\n");
      out.write("         <table id=\"tbl_ticketing\" class=\"tbl_notice\" style=\"text-align: center; margin-top: 30px;\">\r\n");
      out.write("             <tr id = \"ticketing_title\">\r\n");
      out.write("                <th>No</th>\r\n");
      out.write("                <th>예매번호</th>\r\n");
      out.write("                <th>영화명</th>\r\n");
      out.write("                <th>예매좌석</th>\r\n");
      out.write("                <th>상영일시</th>\r\n");
      out.write("                <th>예매일</th>\r\n");
      out.write("                <th class=\"cancelyn\">예매취소</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("              <tbody id=\"ticketing_body\"></tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\".mypoint p\").html(");
      out.print(m.getPoint());
      out.write(");\r\n");
      out.write("var num = 1;\r\n");
      out.write("/* var cancel_yn = \"\"; */\r\n");
      out.write("/*효정수정1 시작*/\r\n");
      out.write("var ticketNo = 0;\r\n");
      out.write("var showDate = '';\r\n");
      out.write("var startTime = '';\r\n");
      out.write("var screenCode = 0;\r\n");
      out.write("var seatNo = '';\r\n");
      out.write("var memberId = '");
      out.print(memberLoggedIn.getMemberId());
      out.write("';\r\n");
      out.write("/*효정수정1 끝*/\r\n");
      out.write("$(()=>{\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#ticketingList\").css(\"color\", \"#503396\").css(\"font-weight\", \"bold\");\r\n");
      out.write("\t\r\n");
      out.write("\treservationList();\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".reservationList\").click(function(){\r\n");
      out.write("\t\t\treservationList();\r\n");
      out.write(" \t\t\t$(this).css(\"color\", \"rgb(98, 80, 211)\");\r\n");
      out.write(" \t\t\t$(\".tab_type02 li a\").not($(this)).css(\"color\", \"gray\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".cancelList\").click(function(){\r\n");
      out.write(" \t\t\tcancelList();\r\n");
      out.write(" \t\t\t$(this).css(\"color\", \"rgb(98, 80, 211)\");\r\n");
      out.write(" \t\t\t$(\".tab_type02 li a\").not($(this)).css(\"color\", \"gray\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function reservationList(){\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/member/memberTicketingList/ticketingList.do\",\r\n");
      out.write("\t\tdata: {memberId: '");
      out.print(memberLoggedIn.getMemberId());
      out.write("'},\t\t\r\n");
      out.write("\t\ttype: \"POST\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess: data => {\r\n");
      out.write("\t\t\t\r\n");
      out.write("/*         \tlet html2 = \"\";\r\n");
      out.write("          \thtml2 += \"<table id='tbl_ticketing' class='tbl_notice' style='text-align: center; margin-top: 30px;'>;\r\n");
      out.write("            html2 += \"<tr id = 'ticketing_title'>\";\r\n");
      out.write("            html2 += \"<th>No</th><th>예매번호</th><th>영화명</th><th>예매좌석</th><th>상영일시</th><th>예매일</th>\";\r\n");
      out.write("            html2 += \"<th class='cancelyn'>예매취소</th></tr>\";\r\n");
      out.write("            html2 += \"<tbody id='ticketing_body'></tbody></table>\";\r\n");
      out.write("            $(\"#tbl_div\").append(html2); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\".cancelyn\").html(\"예매취소\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#ticketing_body\").html(\"\");\r\n");
      out.write("\t\t\tnum = 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(let i in data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet html = \"\";\r\n");
      out.write("\t\t\t\tlet t = data[i];\r\n");
      out.write("\t\t\t\tcancel_yn = t.cancelYN;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+num+\"</td>\"; \r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.ticketNo+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.movieTitle+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.screenCode+\"관</br>\"+t.seatNo+\"열</td>\"; //예매좌석\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.showDate+\"</br>\"+t.startTime+\"~\"+t.endTime+\"</td>\"; //상영일시\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.ticketingDate+\"</td>\";\r\n");
      out.write("/* \t\t\t\thtml += \"<td style='font-weight: bold'>\"+((cancel_yn == 'N') ? \"<a href='javascript:void(0)' style='color: rgb(98, 80, 211);'>X</a></td>\" : \"O</td>\"); */\r\n");
      out.write("\t\t\t\thtml += \"<td style='color: rgb(98, 80, 211); font-weight: bold;'><button id='btn-cancelTicket' onclick='cancelTicket()'>예매취소</button></td>\"/*효정수정2*/\r\n");
      out.write("\t\t\t\thtml += \"</tr>\"\r\n");
      out.write("\t\t\t\t/*효정수정3 시작*/\r\n");
      out.write("\t\t\t\tticketNo = t.ticketNo;\r\n");
      out.write("\t\t\t\tshowDate = t.showDate;\r\n");
      out.write("\t\t\t\tstartTime = t.startTime;\r\n");
      out.write("\t\t\t\tscreenCode = t.screenCode;\r\n");
      out.write("\t\t\t\tseatNo = t.seatNo;\r\n");
      out.write("\t\t\t\t/*효정수정3 끝*/\r\n");
      out.write("\t\t\t\t$(\"#ticketing_body\").append(html);\r\n");
      out.write("\t\t\t\tnum++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : (jqxhr, textStatus, errorThrown)=>{\r\n");
      out.write("\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}); //ajax끝\r\n");
      out.write("\t\r\n");
      out.write("} //function reservationList끝\r\n");
      out.write("\r\n");
      out.write("function cancelList(){\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/member/memberTicketingList/cancelList.do\",\r\n");
      out.write("\t\tdata: {memberId: '");
      out.print(memberLoggedIn.getMemberId());
      out.write("'},\t\t\r\n");
      out.write("\t\ttype: \"POST\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess: data => {\r\n");
      out.write("\t\t\t$(\".cancelyn\").html(\"예매취소일\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#ticketing_body\").html(\"\");\r\n");
      out.write("\t\t\tnum = 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(let i in data){\r\n");
      out.write("\t\t\t\tlet html = \"\";\r\n");
      out.write("\t\t\t\tlet t = data[i];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+num+\"</td>\"; \r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.ticketNo+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.movieTitle+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.screenCode+\"관</br>\"+t.seatNo+\"열</td>\"; //예매좌석\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.showDate+\"</br>\"+t.startTime+\"~\"+t.endTime+\"</td>\"; //상영일시\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.ticketingDate+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+t.cancelDate+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"</tr>\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#ticketing_body\").append(html);\r\n");
      out.write("\t\t\t\tnum++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : (jqxhr, textStatus, errorThrown)=>{\r\n");
      out.write("\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}); //ajax끝\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("/*효정수정4 시작*/\r\n");
      out.write("function cancelTicket(){\r\n");
      out.write("\tlocation.href = '");
      out.print(request.getContextPath());
      out.write("/member/memberTicketingCancel?showDate='+showDate+\"&startTime=\"+startTime+\"&ticketNo=\"+ticketNo+\"&screenCode=\"+screenCode+\"&seatNo=\"+seatNo+\"&memberId=\"+memberId;\r\n");
      out.write("}\r\n");
      out.write("/*효정수정4 끝*/\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\"> -->\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!-- 풋터 -->\n");
      out.write("<footer class=\"foot\">\n");
      out.write("    <div id=bottomFoot class=\"bottom_foot\">\n");
      out.write("        <ul class=\"div-bottomfoot\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">공지사항\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">고객센터\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이용약관\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이벤트\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">스토어바로가기\n");
      out.write("            </li>\n");
      out.write("        </ul>           \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- 풋터 안 인포메이션 -->\n");
      out.write("    <div id=\"infoFoot\" class=\"info_foot\">\n");
      out.write("                                \n");
      out.write("        <span>사업자정보확인</span> <span>개인정보관리자</span><span>통신판매 신고번호 제 00000123123호</span> <br><br>\n");
      out.write("        <span>대표이사: NONAME</span> <span>본점: 서울특별시 서초구 서초동 123-456</span> <span>사업장: 서울특별시 마포구 상암로 123 상암동 456</span><br><br>\n");
      out.write("        <span>고객센터: 1234-5678</span> <span>NOTITLE문의: 02-1234-5678</span> <span>NOTITLE문의:  csnotitle@notitle.com</span>\n");
      out.write("        \n");
      out.write("    <h3>PIXARBOX</h3>\n");
      out.write("    </div><!-- div.info_foot div-->\n");
      out.write("\n");
      out.write("    <div class=\"end_foot\">\n");
      out.write("        InsideOut\n");
      out.write("    </div><!--div.end_foot-->\n");
      out.write("    <!-- 풋터 안 인포메이션 끝 -->\n");
      out.write("</footer>\n");
      out.write("    <!-- 풋터 끝 -->   \n");
      out.write("            \n");
      out.write("            \n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
