/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-06 01:44:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class memberUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577923558000L));
    _jspx_dependants.put("/WEB-INF/views/common/mypageHeader.jsp", Long.valueOf(1578160788000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	//로그인한 경우
	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	
	//쿠키관련
	boolean saveId = false;
	String loginId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();
			
			if("saveId".equals(k)) {
				saveId = true;
				loginId = v;
			}
		}
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>PIXARBOX</title>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<!--웹폰트추가  -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Anton|Do+Hyeon|Nanum+Gothic+Coding&display=swap&subset=latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 두번째 헤더 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 고정헤더 -->\r\n");
      out.write("\t    <nav id=\"topUtil\" class=\"top_util\">\r\n");
      out.write("\t        <span>PIXAR</span>\r\n");
      out.write("\t        <ul class=\"nav\">\r\n");
      out.write("\t        ");
 if(memberLoggedIn == null) { 
      out.write("\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogin\" id=\"login_btn\">로그인</a>        \r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=\"sign_btn\">회원가입</a>   \r\n");
      out.write("\t\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t        ");
 }
	        else { 
      out.write("\r\n");
      out.write("\t        \t<li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \r\n");
      out.write("\t\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a>   \r\n");
      out.write("\t\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"mypage_btn\">마이페이지</a>   \r\n");
      out.write("\t            </li>\r\n");
      out.write("\t            <li>\r\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t    ");
 } 
      out.write("\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 기본 헤더와 다른 마이페이지 부분 -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section-mypage-top\">\r\n");
      out.write("\t\t<div class=\"mypage-top-left\">\r\n");
      out.write("\t\t\t<strong class=\"mypage-id\" id=\"nickname\">");
      out.print(memberLoggedIn.getLastName()+memberLoggedIn.getFirstName() );
      out.write(" <span>님</span>\r\n");
      out.write("\t\t\t</strong>\r\n");
      out.write("\t\t\t<div class=\"mypoint\">\r\n");
      out.write("\t\t\t\t<span>포인트</span>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>");
      out.print(memberLoggedIn.getPoint() );
      out.write("</strong>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 헤더 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"tab_type01\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" id=\"pointList\">포인트내역</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/like.do?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" id=\"likeList\">찜</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/purchase.do?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\" id=\"ticketingList\">예매내역</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/update.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"modifyMemberInfo\">개인정보수정</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write('\r');
      out.write('\n');

	Member m = (Member)request.getAttribute("member");
	
	//이메일 셀렉티드처리
	String emailSelected[] = {"", "", "", ""};
	String email[] = null;
	
	if(m.getEmail() != null) {
		email = m.getEmail().split("@");
		
		if("hanmail.net".equals(email[1])) emailSelected[0] = "selected";
		else if("daum.net".equals(email[1])) emailSelected[1] = "selected";
		else if("naver.com".equals(email[1])) emailSelected[2] = "selected";
		else if("gmail.com".equals(email[1])) emailSelected[3] = "selected";
		//System.out.println(email[1]);
		/* for(String e : email) {
			switch(e) {
			case "hanmail.net": emailSelected[0] = "selected"; break;
			case "daum.net": emailSelected[1] = "selected"; break;
			case "naver.com": emailSelected[2] = "selected"; break;
			case "gmail.com": emailSelected[3] = "selected"; break;
			}
		} */
	}
	
	//관심장르 체크드처리
	String interestsChecked[] = {"", "", "", "", "", "", "", "", "", "", ""};
	
	if(m.getInterests() != null) {
		String interests[] = m.getInterests().split(",");
		
		for(String i : interests) {
			switch(i) {
			case "드라마": interestsChecked[0] = "checked"; break;
			case "판타지": interestsChecked[1] = "checked"; break;
			case "아동": interestsChecked[2] = "checked"; break;
			case "코미디": interestsChecked[3] = "checked"; break;
			case "어드벤처": interestsChecked[4] = "checked"; break;
			case "가족": interestsChecked[5] = "checked"; break;
			case "SF": interestsChecked[6] = "checked"; break;
			case "뮤지컬": interestsChecked[7] = "checked"; break;
			case "애니메이션": interestsChecked[8] = "checked"; break;
			case "모험": interestsChecked[9] = "checked"; break;
			case "액션": interestsChecked[10] = "checked"; break;
			}
		}

		//System.out.println(Arrays.toString(interests));
	}
	
	String genderChecked[] = {"", ""};
	
	if(m.getGender() != null) {
		if("F".equals(m.getGender())) genderChecked[0] = "checked";
		else if("M".equals(m.getGender())) genderChecked[1] = "checked";
	}
	
	String ageChecked[] = {"", "", "", "", "", ""};
	
	if(m.getAge()+"" != null) {
		if("10".equals(m.getAge()+"")) ageChecked[0] = "checked";
		else if("20".equals(m.getAge()+"")) ageChecked[1] = "checked";
		else if("30".equals(m.getAge()+"")) ageChecked[2] = "checked";
		else if("40".equals(m.getAge()+"")) ageChecked[3] = "checked";
		else if("50".equals(m.getAge()+"")) ageChecked[4] = "checked";
		else if("60".equals(m.getAge()+"")) ageChecked[5] = "checked";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/css/member.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/css/mypage.css\" />\r\n");
      out.write("\r\n");
      out.write("<section id=\"content-member\">\r\n");
      out.write("\t<h2>정보수정</h2>\r\n");
      out.write("\t<div class=\"title\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"enrollFrm\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberUpdate\"\r\n");
      out.write("\t\t\tname=\"memberUpdateForm\" method=\"post\" id=\"enrollForm\"\r\n");
      out.write("\t\t\tonsubmit=\"return updateValidate();\">\r\n");
      out.write("\t\t\t<!-- 92번줄 p 기본정보 태그에 id값추가  -->\r\n");
      out.write("\t\t\t<p id=\"p_border_left\">기본정보</p>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"lastName\" id=\"lastName\" placeholder=\"성\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 60px;\" value=\"");
      out.print(m.getLastName() );
      out.write("\" required>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"firstName\" id=\"firstName\" placeholder=\"이름\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 145px;\" value=\"");
      out.print(m.getFirstName() );
      out.write("\" required>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br> <input type=\"text\" name=\"memberId\" id=\"memberId\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 230px;\" value=\"");
      out.print(m.getMemberId() );
      out.write("\" required\r\n");
      out.write("\t\t\t\treadonly>&nbsp; <input type=\"hidden\" id=\"idValid\" value=\"0\" />\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br> \r\n");
      out.write("\t\t\t<!--비밀번호 변경 input태그에 id값추가 id=\"pwd\"  -->\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"pwd\" value=\"비밀번호 변경\"\r\n");
      out.write("\t\t\t\tonclick=\"updatePassword();\" /> <br>\r\n");
      out.write("\t\t\t<br> <input type=\"text\" name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\tplaceholder=\"이메일\" style=\"width: 100px;\" value=\"");
      out.print(email[0] );
      out.write("\"\r\n");
      out.write("\t\t\t\trequired> @ <select name=\"emailAdd\" id=\"emailAdd\"\r\n");
      out.write("\t\t\t\t>\r\n");
      out.write("\t\t\t\t<!--위에 스타일삭제  -->\r\n");
      out.write("\t\t\t\t<option value=\"hanmail.net\" ");
      out.print(emailSelected[0] );
      out.write(">hanmail.net</option>\r\n");
      out.write("\t\t\t\t<option value=\"daum.net\" ");
      out.print(emailSelected[1] );
      out.write(">daum.net</option>\r\n");
      out.write("\t\t\t\t<option value=\"naver.com\" ");
      out.print(emailSelected[2] );
      out.write(">naver.com</option>\r\n");
      out.write("\t\t\t\t<option value=\"gmail.com\" ");
      out.print(emailSelected[3] );
      out.write(">gmail.com</option>\r\n");
      out.write("\t\t\t</select> <br>\r\n");
      out.write("\t\t\t<br> <input type=\"tel\" name=\"phone1\" id=\"phone1\"\r\n");
      out.write("\t\t\t\tplaceholder=\"010\" maxlength=\"3\" style=\"width: 50px;\" value=\"010\"\r\n");
      out.write("\t\t\t\trequired>&nbsp;- <input type=\"tel\" name=\"phone2\" id=\"phone2\"\r\n");
      out.write("\t\t\t\tplaceholder=\"1234\" maxlength=\"4\" style=\"width: 70px;\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(m.getPhone().substring(3, 7) );
      out.write("\" required>&nbsp;-\r\n");
      out.write("\t\t\t<input type=\"tel\" name=\"phone3\" id=\"phone3\" placeholder=\"5678\"\r\n");
      out.write("\t\t\t\tmaxlength=\"4\" style=\"width: 70px;\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(m.getPhone().substring(7) );
      out.write("\" required> <br>\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t<p id=\"p_border_gender\">성별\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" id=\"gender0\" value=\"F\" ");
      out.print(genderChecked[0] );
      out.write(" />여자\r\n");
      out.write("\t\t    <input type=\"radio\" name=\"gender\" id=\"gender1\" value=\"M\" ");
      out.print(genderChecked[1] );
      out.write(" />남자\r\n");
      out.write("\t\t   </p>\r\n");
      out.write("\t\t    <br /><br />\r\n");
      out.write("\t\t    <!--130번줄 연령 p태그 추가  -->\r\n");
      out.write("\t\t    <p id=\"p_border\">연령</p>\r\n");
      out.write("\t\t    <input type=\"radio\" name=\"age\" id=\"age10\" value=\"10\" ");
      out.print(ageChecked[0] );
      out.write(" />10대\r\n");
      out.write("\t\t    <input type=\"radio\" name=\"age\" id=\"age20\" value=\"20\" ");
      out.print(ageChecked[1] );
      out.write(" />20대\r\n");
      out.write("\t\t    <input type=\"radio\" name=\"age\" id=\"age30\" value=\"30\" ");
      out.print(ageChecked[2] );
      out.write(" />30대\r\n");
      out.write("\t\t    <input type=\"radio\" name=\"age\" id=\"age40\" value=\"40\" ");
      out.print(ageChecked[3] );
      out.write(" />40대\r\n");
      out.write("\t\t    <!--아래 br태그추가  -->\r\n");
      out.write("\t\t    <br>\r\n");
      out.write("\t\t    <input type=\"radio\" name=\"age\" id=\"age50\" value=\"50\" ");
      out.print(ageChecked[4] );
      out.write(" />50대\r\n");
      out.write("\t\t    <input type=\"radio\" name=\"age\" id=\"age60\" value=\"60\" ");
      out.print(ageChecked[5] );
      out.write(" />60대 이상\r\n");
      out.write("\t\t\t<br /><br /><br> \r\n");
      out.write("\t\t\t<p id=\"p_border\">관심장르</p>\r\n");
      out.write("\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"genre\"\r\n");
      out.write("\t\t\t\t\tid=\"genre1\" value=\"드라마\" ");
      out.print(interestsChecked[0] );
      out.write("> <label class=\"form-check-label\"\r\n");
      out.write("\t\t\t\t\tfor=\"genre1\"  >드라마</label> \r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\"\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"genre\" id=\"genre2\" value=\"판타지\" ");
      out.print(interestsChecked[1] );
      out.write("> <label\r\n");
      out.write("\t\t\t\t\tclass=\"form-check-label\" for=\"genre2\"  >판타지</label>\r\n");
      out.write("\t\t\t \t<input\r\n");
      out.write("\t\t\t\t\tclass=\"form-check-input\" type=\"checkbox\" name=\"genre\" id=genre3\r\n");
      out.write("\t\t\t\t\tvalue=\"아동\"  ");
      out.print(interestsChecked[2] );
      out.write("> <label class=\"form-check-label\" for=\"genre3\">아동</label>\r\n");
      out.write("\t\t\t\t<br /><br/>\r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"genre\"\r\n");
      out.write("\t\t\t\t\tid=\"genre4\" value=\"코미디\" ");
      out.print(interestsChecked[3] );
      out.write("> <label class=\"form-check-label\"\r\n");
      out.write("\t\t\t\t\tfor=\"genre4\"  >코미디</label> \r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\"\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"genre\" id=\"genre5\" value=\"어드벤처\" ");
      out.print(interestsChecked[4] );
      out.write("> <label\r\n");
      out.write("\t\t\t\t\tclass=\"form-check-label\" for=\"genre5\"  >어드벤처</label> \r\n");
      out.write("\t\t\t\t<input\r\n");
      out.write("\t\t\t\t\tclass=\"form-check-input\" type=\"checkbox\" name=\"genre\" id=\"genre6\"\r\n");
      out.write("\t\t\t\t\tvalue=\"가족\"  ");
      out.print(interestsChecked[5] );
      out.write("> <label class=\"form-check-label\" for=\"genre6\" >가족</label>\r\n");
      out.write("\t\t\t\t<br /><br/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"genre\"\r\n");
      out.write("\t\t\t\t\tid=\"genre7\" value=\"SF\"  ");
      out.print(interestsChecked[6] );
      out.write("> <label class=\"form-check-label\"\r\n");
      out.write("\t\t\t\t\tfor=\"genre7\">SF</label> \r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\"\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"genre\" id=\"genre8\" value=\"뮤지컬\" ");
      out.print(interestsChecked[7] );
      out.write("> <label\r\n");
      out.write("\t\t\t\t\tclass=\"form-check-label\" for=\"genre8\"  >뮤지컬</label> \r\n");
      out.write("\t\t\t\t<input\r\n");
      out.write("\t\t\t\t\tclass=\"form-check-input\" type=\"checkbox\" name=\"genre\" id=\"genre9\"\r\n");
      out.write("\t\t\t\t\tvalue=\"애니메이션\"  ");
      out.print(interestsChecked[8] );
      out.write("> <label class=\"form-check-label\" for=\"genre9\">애니메이션</label>\r\n");
      out.write("\t\t\t\t<br /><br/>\r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"genre\"\r\n");
      out.write("\t\t\t\t\tid=\"genre10\" value=\"모험\"  ");
      out.print(interestsChecked[9] );
      out.write("> <label class=\"form-check-label\"\r\n");
      out.write("\t\t\t\t\tfor=\"genre10\">모험</label> \r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\"\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"genre\" id=\"genre11\" value=\"액션\"  ");
      out.print(interestsChecked[10] );
      out.write("> <label\r\n");
      out.write("\t\t\t\t\tclass=\"form-check-label\" for=\"genre11\">액션</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"point\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(memberLoggedIn.getPoint() );
      out.write("\" /> \r\n");
      out.write("\t\t\t\t<input type=\"submit\" id=\"edit\" value=\"정보수정\" /> \r\n");
      out.write("\t\t\t\t<input type=\"reset\" id=\"rset\" value=\"초기화\" /> \r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"탈퇴\" onclick=\"confirmDelete();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("$(\".mypoint p\").html(");
      out.print(m.getPoint());
      out.write(");\r\n");
      out.write("\t$(()=> {\r\n");
      out.write("\t\t$(\"#modifyMemberInfo\").css(\"color\", \"#503396\").css(\"font-weight\", \"bold\");\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction updatePassword() {\r\n");
      out.write("\t\tvar url = \"");
      out.print(request.getContextPath() );
      out.write("/member/updatePassword?memberId=");
      out.print(m.getMemberId() );
      out.write("\";\r\n");
      out.write("\t\tvar title = \"updatePasswordPopup\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar width = 500;\r\n");
      out.write("        var height = 300;\r\n");
      out.write("        var screenWidth = screen.availWidth;\r\n");
      out.write("        var screenHeight = screen.availHeight;\r\n");
      out.write("        \r\n");
      out.write("\t\tvar spec = \"left=\"+(screenWidth-width)/2+\", top=\"+(screenHeight-height)/2+\", width=\"+width+\", height=\"+height;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\topen(url,title, spec);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction confirmDelete() {\r\n");
      out.write("\t\tif(confirm(\"정말로 탈퇴하시겠습니까?\"))\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath() );
      out.write("/member/memberDelete?memberId=");
      out.print(m.getMemberId() );
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\"> -->\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!-- 풋터 -->\n");
      out.write("<footer class=\"foot\">\n");
      out.write("    <div id=bottomFoot class=\"bottom_foot\">\n");
      out.write("        <ul class=\"div-bottomfoot\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">공지사항\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">고객센터\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이용약관\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이벤트\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">스토어바로가기\n");
      out.write("            </li>\n");
      out.write("        </ul>           \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- 풋터 안 인포메이션 -->\n");
      out.write("    <div id=\"infoFoot\" class=\"info_foot\">\n");
      out.write("                                \n");
      out.write("        <span>사업자정보확인</span> <span>개인정보관리자</span><span>통신판매 신고번호 제 00000123123호</span> <br><br>\n");
      out.write("        <span>대표이사: NONAME</span> <span>본점: 서울특별시 서초구 서초동 123-456</span> <span>사업장: 서울특별시 마포구 상암로 123 상암동 456</span><br><br>\n");
      out.write("        <span>고객센터: 1234-5678</span> <span>NOTITLE문의: 02-1234-5678</span> <span>NOTITLE문의:  csnotitle@notitle.com</span>\n");
      out.write("        \n");
      out.write("    <h3>PIXARBOX</h3>\n");
      out.write("    </div><!-- div.info_foot div-->\n");
      out.write("\n");
      out.write("    <div class=\"end_foot\">\n");
      out.write("        InsideOut\n");
      out.write("    </div><!--div.end_foot-->\n");
      out.write("    <!-- 풋터 안 인포메이션 끝 -->\n");
      out.write("</footer>\n");
      out.write("    <!-- 풋터 끝 -->   \n");
      out.write("            \n");
      out.write("            \n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
