/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-07 00:16:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ticket;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import theater.model.vo.Seat;
import member.model.vo.Member;
import java.util.List;

public final class ticketingStep2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578022508000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577923558000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("theater.model.vo.Seat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');

	//로그인한 경우
	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	//System.out.println("memberLoggedIn@header.jsp="+memberLoggedIn);

	//쿠키관련
	boolean saveId = false;
	String loginId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();
			
			if("saveId".equals(k)) {
				saveId = true;
				loginId = v;
			}
		}
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>PIXARBOX</title>\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("<!--웹폰트추가  -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Anton|Do+Hyeon|Nanum+Gothic+Coding&display=swap&subset=latin-ext,vietnamese\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script> -->\n");
      out.write("\n");
      out.write("<!--슬라이드코드추가--> \n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 파비콘추가-->\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 헤더  -->\n");
      out.write("<header id=\"header\" class=\"header_main\">\n");
      out.write("\n");
      out.write("<!-- 두번째 헤더 -->\n");
      out.write("    <div class=\"sec_haed\">\n");
      out.write("\t    <!-- 고정헤더 -->\n");
      out.write("\t    <nav id=\"topUtil\" class=\"top_util\">\n");
      out.write("\t        <span>PIXAR</span>\n");
      out.write("\t        <ul class=\"nav\">\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 if(memberLoggedIn == null) { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogin\" id=\"login_btn\">로그인</a>        \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=\"sign_btn\">회원가입</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 }
	        else if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())) { 
	        
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t        \t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\" id=\"admin_btn\">관리자페이지</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a></li>\n");
      out.write("\t        ");
 }
	        else { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"mypage_btn\">마이페이지</a>   \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t    ");
 } 
      out.write("\n");
      out.write("\t        </ul>\n");
      out.write("\t    </nav>\n");
      out.write("\t<!-- 고정헤더 끝 -->\n");
      out.write("        <nav id=\"secUtil\" class=\"sec_util\">\n");
      out.write("            \n");
      out.write("            <span>\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">PIXAR<br><br>BOX</a>\n");
      out.write("            </span>\n");
      out.write("                \n");
      out.write("            <ul class=\"nav-sec\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/ticket/ticketingStep1/step1.do\">예매</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/movie/boxOffice/order1.do\">영화</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/theater/theaterInfo\">영화관</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">이벤트</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">스토어</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">VOD</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </div><!--div.sec_haed-->\n");
      out.write("    <!-- 두번째 헤더 끝 -->\n");
      out.write("</header>\n");
      out.write("<!-- 헤더 끝 -->\n");
      out.write("\n");
      out.write("<!-- <section id=\"content\"> -->\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/ticketStep2.css\" />\r\n");
      out.write("<link href=\"http://www.jqueryscript.net/css/jquerysctipttop.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/jquery.seat-charts.css\">\r\n");
 
	int showCode = (int)request.getAttribute("showCode");
    //System.out.println(showCode);
    int showTurn = Integer.parseInt((String)request.getAttribute("showTurn"));
    List<Seat> seatList = (List<Seat>)request.getAttribute("seatList");
    int rowsNum = (int)request.getAttribute("rowsNum");
    int colsNum = (int)request.getAttribute("colsNum");
    //System.out.println(seatList);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(()=>{\r\n");
      out.write("\t");

		//상영관마다 장애인석 표시
  		if(seatList.get(1).getScreenCode() == 1 || seatList.get(1).getScreenCode() == 5){
  	
      out.write("\r\n");
      out.write("  \t\t\t\t$(\"#A11, #A12\").css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("  \t\t\t\t$(\"#A11, #A12\").addClass(\"disabledSeat\");\r\n");
      out.write(" \t");

  		}
  		else if(seatList.get(1).getScreenCode() == 2 || seatList.get(1).getScreenCode() == 3 || seatList.get(1).getScreenCode() == 4){
	
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#A10, #A11\").css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("\t\t\t\t$(\"#A10, #A11\").addClass(\"disabledSeat\");\r\n");
      out.write("\t");

		}
		for(Seat s : seatList){
			//예매완료 표시		
			if(s.getReservationYN().equals("Y")){
	
      out.write("\r\n");
      out.write("\t\t\t \t$(\"#");
      out.print(s.getSeatNo());
      out.write("\").css(\"background\",\"rgb(224, 224, 224)\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t .css(\"cursor\", \"not-allowed\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t .css(\"pointer-events\", \"none\");\r\n");
      out.write("\t\t\t \t$(\"#");
      out.print(s.getSeatNo());
      out.write("\").addClass(\"Y\");\r\n");
      out.write("\t");
			
			}
		}
	
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var showCode = ");
      out.print(showCode);
      out.write(";\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\tvar m = {\r\n");
      out.write("\t\t\tshowCode: showCode\r\n");
      out.write("\t}\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/ticket/ticketingStep2/selectMovieInfo.do\",\r\n");
      out.write("\t\ttype: \"get\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tdata: m,\r\n");
      out.write("\t\tsuccess: data => {\r\n");
      out.write("\t\t\t//console.log(data);//json문자열, javascript object\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(data).each((idx, movieSeat)=>{\r\n");
      out.write("\t\t\t\tlet html=\"<tr><td colspan='2'><img src='");
      out.print(request.getContextPath());
      out.write("/images/\"+movieSeat.renamedFileName+\"' id='movieImg'></td></tr>\";\r\n");
      out.write("\t\t\t\thtml+=\"<tr><td colspan='2' class='bold'>\"+movieSeat.movieTitle+\"<span style='padding-left: 20px; font-weight: bold; color: #35256B;'>");
      out.print(showTurn==1?"조조":"");
      out.write("</span></td></tr>\";\r\n");
      out.write("\t\t\t\thtml+=\"<td>일시</td><td class='bold'>\"+movieSeat.showDate+\"</td></tr>\";\r\n");
      out.write("\t\t\t\thtml+=\"<tr><td>상영시간</td><td class='bold'>\"+movieSeat.startTime+\"~\"+movieSeat.endTime+\"</td></tr>\";\r\n");
      out.write("\t\t\t\thtml+=\"<tr><td>상영관</td><td class='bold'>\"+movieSeat.screenCode+\"관\"+\"</td></tr>\";\r\n");
      out.write("\t\t\t\thtml+=\"<tr><td>남은좌석</td><td class='bold'><p id='red'>\"+movieSeat.remainSeats+\"</p>/\"+movieSeat.seatCnt+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t$(\"#movieInfo\").append(html);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : (jqxhr, textStatus, errorThrown)=>{\r\n");
      out.write("\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("function getStep3(){\r\n");
      out.write("\tselectedSeat = $(\".getResult\").text();\r\n");
      out.write("\tadult = $(\".adultSeat\").length;\r\n");
      out.write("\tchild = $(\".childSeat\").length;\r\n");
      out.write("\tspecial = $(\".specialSeat\").length;\r\n");
      out.write("\ttotal = $(\"#total\").html();\r\n");
      out.write("\t\r\n");
      out.write("\tif(0 < currentVal < 9 && currentVal == $(\".clicked\").length && selectedSeat != \"\"){\t\t\r\n");
      out.write("\t\tlocation.href='");
      out.print(request.getContextPath());
      out.write("/ticket/ticketingStep3/step3.do?showCode='+showCode+\"&selectedSeat=\"+selectedSeat+\"&total=\"+total+\"&adult=\"+adult+\"&child=\"+child+\"&special=\"+special+\"&memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\";\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tif(currentVal == 0)\r\n");
      out.write("\t\t\talert(\"최소 1명 이상의 인원을 선택하세요.\");\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\talert(\"예매 인원과 선택 인원이 일치하지 않습니다.\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function getPrevious(){\r\n");
      out.write("\tlocation.href='");
      out.print(request.getContextPath());
      out.write("/ticket/ticketingStep1/step1.do';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<section id=\"content-ticketingStep2\">\r\n");
      out.write("\t\t  <h2>인원/좌석 선택</h2>\r\n");
      out.write("\t<div class=\"jquery-script-clear\"></div>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t  \t<div class=\"step2Container\">\r\n");
      out.write("\t    <div id=\"seat-map\">\r\n");
      out.write("\t\t  <br><br>\r\n");
      out.write("\t\t\t<div id=\"sort\">\r\n");
      out.write("\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t<p>일반</p>\r\n");
      out.write("\t\t\t\t<input type=\"number\" class=\"sort\" id=\"adult\" max=\"8\" min=\"0\" placeholder=\"0\">\r\n");
      out.write("\t\t\t\t<p>청소년</p>\r\n");
      out.write("\t\t\t\t<input type=\"number\" class=\"sort\" id=\"child\" max=\"8\" min=\"0\" placeholder=\"0\">\r\n");
      out.write("\t\t\t\t<p>우대</p>\r\n");
      out.write("\t\t\t\t<input type=\"number\" class=\"sort\" id=\"special\" max=\"8\" min=\"0\" placeholder=\"0\">\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"다시선택\" id=\"btn-reset\" style=\"background: #35256B; color: white; border:0; border-radius: 2px; height: 23px\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<span style=\"padding-left: 35px; font-size: 12px; font-weight: bold;\">* 최대 선택 인원은 8명입니다.</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  <div class=\"front-indicator\">Front</div>\r\n");
      out.write("\t\t  <fieldset>\r\n");
      out.write("              <legend>좌석 설정</legend>\r\n");
      out.write("              <p><label>행 : <input type=\"number\" name=\"cols\" value=\"12\" /></label></p>\r\n");
      out.write("              <p><label>열 : <input type=\"number\" name=\"rows\" value=\"7\" /></label></p>\r\n");
      out.write("          </fieldset>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            <div class=\"wrap\">\r\n");
      out.write("              \t<ul class=\"rowsHead\"></ul>\r\n");
      out.write("                <ol class=\"seat\"></ol>\r\n");
      out.write("           </div>\r\n");
      out.write("            \r\n");
      out.write("\t\t \r\n");
      out.write("\t</div>\r\n");
      out.write("    <div id=\"seat-charts\">\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("\t\t    <li>\r\n");
      out.write("\t\t        <div id=\"select-seat\"></div>\r\n");
      out.write("\t\t        <span>선택좌석</span>\r\n");
      out.write("\t\t    </li>\r\n");
      out.write("\t\t    <li>\r\n");
      out.write("\t\t        <div id=\"ticketingEnd-seat\"></div>\r\n");
      out.write("\t\t    \t<span>예매완료</span>\r\n");
      out.write("\t\t    </li>\r\n");
      out.write("\t\t    <li>\r\n");
      out.write("\t\t         <div id=\"avaliable-seat\"></div>\r\n");
      out.write("\t\t         <span>선택가능</span>\r\n");
      out.write("\t\t    </li>\r\n");
      out.write("\t\t    <li>\r\n");
      out.write("\t\t         <div id=\"special-seat\"></div>\r\n");
      out.write("\t\t         <span>장애인석</span>\r\n");
      out.write("\t\t    </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("   </div>\r\n");
      out.write("\t<div id=\"movie-box\">\r\n");
      out.write("\t\t<table id=\"movieInfo\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t    <table id=priceInfo>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t            <td rowspan=\"1\">\r\n");
      out.write("\t                <div id=\"btn-previous\" onclick=\"getPrevious()\">\r\n");
      out.write("\t                    <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/previous.png\" alt=\"\" id=\"img-previous\">\r\n");
      out.write("\t                    <p>이전</p>                    \r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </td>\r\n");
      out.write("\t            <td>인원</td>\r\n");
      out.write("\t            <td id=personnel>일반 <span id=\"adult_counter\">0</span>명</td>\r\n");
      out.write("\t            <td id=blank></td>\r\n");
      out.write("\t            <td>좌석</td>\r\n");
      out.write("\t            <td id=\"selected-seats\"><div class=\"result\"></div></td>\r\n");
      out.write("\t            <td id=blank></td>\r\n");
      out.write("\t            <td id=blank></td>\r\n");
      out.write("\t            <td>결제금액</td>\r\n");
      out.write("\t            <td id=\"totalPrice\"><span id=\"total\">0</span></td>\r\n");
      out.write("\t\t\t\t<td>원</td>\r\n");
      out.write("\t\t\t\t<td id=blank></td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"결제선택\" id=\"paymentButton\"\r\n");
      out.write("\t\t\t\t\t       onclick=getStep3()>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t        \t</tr>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t        \t<td></td>\r\n");
      out.write("\t        \t<td></td>\r\n");
      out.write("\t            <td style=\"padding-left: 10px; font-weight: bold; font-size: 20px;\">청소년 <span id=\"child_counter\">0</span>명</td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t        \t<td></td>\r\n");
      out.write("\t        \t<td></td>\r\n");
      out.write("\t            <td style=\"padding-left: 11px; font-weight: bold; font-size: 20px;\">우대 <span id=\"special_counter\">0</span>명</td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t    </table>\r\n");
      out.write("\t    \r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var adultVal = Number($(\"#adult\").val());\r\n");
      out.write("var childVal = Number($(\"#child\").val());\r\n");
      out.write("var specialVal = Number($(\"#special\").val());\r\n");
      out.write("var currentVal = currentVal = adultVal + childVal + specialVal;\r\n");
      out.write("var selectedSeat = '';\r\n");
      out.write("var total = 0;\r\n");
      out.write("var adult = 0;\r\n");
      out.write("var child = 0;\r\n");
      out.write("var special = 0;\r\n");
      out.write("\r\n");
      out.write("var $cols = $('input[name=cols]'),\r\n");
      out.write("    $rows = $('input[name=rows]'),\r\n");
      out.write("    $result = $('.result'),\r\n");
      out.write("    $seat = $('.wrap .seat'),\r\n");
      out.write("    $colsHead = $('.wrap .colsHead'),\r\n");
      out.write("    $rowsHead = $('.wrap .rowsHead'),\r\n");
      out.write("    $counter = $(\"#counter\"),\r\n");
      out.write("    colsNum = 0, rowsNum = 0;\r\n");
      out.write("\r\n");
      out.write("var result = '';\r\n");
      out.write("\r\n");
      out.write("//가격\r\n");
      out.write("if(");
      out.print(showTurn);
      out.write(" == 1){\r\n");
      out.write("\tvar adultPrice = 7000;\r\n");
      out.write("\tvar childPrice = 6000;\r\n");
      out.write("\tvar specialPrice = 5000;\r\n");
      out.write("}\r\n");
      out.write("else{\r\n");
      out.write("\tvar adultPrice = 11000;\r\n");
      out.write("\tvar childPrice = 9000;\r\n");
      out.write("\tvar specialPrice = 5000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var totalPrice = 0;\r\n");
      out.write("\r\n");
      out.write("$(\"#btn-reset\").click(function(){\r\n");
      out.write("\t//인원 초기화\r\n");
      out.write("\t$(\"#adult_counter\").html(0);\r\n");
      out.write("\t$(\"#child_counter\").html(0);\r\n");
      out.write("\t$(\"#special_counter\").html(0);\r\n");
      out.write("\t//가격\r\n");
      out.write("\t$(\"#total\").html(0);\r\n");
      out.write("\ttotalPrice = 0;\r\n");
      out.write("\t//좌석\r\n");
      out.write("\t$(\".seat li\").not($(\".Y, .disabledSeat\")).css(\"background\", \"gray\");\r\n");
      out.write("\t$(\".disabledSeat\").not($(\".Y\")).css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("\t$(\".seat li\").removeClass(\"clicked\");\r\n");
      out.write("\t$(\".seat li\").removeClass(\"adultSeat\");\r\n");
      out.write("\t$(\".seat li\").removeClass(\"childSeat\");\r\n");
      out.write("\t$(\".seat li\").removeClass(\"specialSeat\");\r\n");
      out.write("\t$result.html(\"\");\r\n");
      out.write("\tresult=\"\";\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$seat.on('click', 'li', function(){\r\n");
      out.write("\tif(currentVal == 0){\r\n");
      out.write("\t\talert(\"최소 1명 이상의 인원을 선택하세요.\");\r\n");
      out.write("\t\t$result.html(\"\");\r\n");
      out.write("\t\tresult=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(currentVal > 8){\r\n");
      out.write("\t\talert(\"인원 선택은 최대 8명까지 가능합니다.\");\r\n");
      out.write("    \t$result.html(\"\");\r\n");
      out.write("    \tresult=\"\";\r\n");
      out.write("    \t$(\".sort\").val(0);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif($(\".clicked\").length == currentVal && currentVal != 0){\r\n");
      out.write("\t\talert(\"이미 좌석을 모두 선택하셨습니다!\");\r\n");
      out.write("\t} \r\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write("//인원 선택 할 때\r\n");
      out.write("$(\".sort\").change(function(){\r\n");
      out.write("\tadultVal = Number($(\"#adult\").val());\r\n");
      out.write("\tchildVal = Number($(\"#child\").val());\r\n");
      out.write("\tspecialVal = Number($(\"#special\").val());\r\n");
      out.write("\tcurrentVal = adultVal + childVal + specialVal;\r\n");
      out.write("\t//console.log(\"선택 인원: \"+currentVal);\r\n");
      out.write("\t\r\n");
      out.write("\t//현재 선택된 좌석보다 인원 선택 수 작게 선택할 시\r\n");
      out.write("\tif(currentVal < $(\".clicked\").length && currentVal != 0){\r\n");
      out.write("\t\talert(\"선택한 좌석의 수가 예매인원보다 많습니다.\");\r\n");
      out.write("\t\t//전부 초기화\r\n");
      out.write("\t    //인원 초기화\r\n");
      out.write("\t\t$(\"#adult_counter\").html(0);\r\n");
      out.write("\t\t$(\"#child_counter\").html(0);\r\n");
      out.write("\t\t$(\"#special_counter\").html(0);\r\n");
      out.write("\t\t//가격\r\n");
      out.write("\t\t$(\"#total\").html(0);\r\n");
      out.write("\t\ttotalPrice = 0;\r\n");
      out.write("\t\t//좌석\r\n");
      out.write("\t\t$(\".seat li\").not($(\".Y, .disabledSeat\")).css(\"background\", \"gray\");\r\n");
      out.write("\t\t$(\".disabledSeat\").not($(\".Y\")).css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"clicked\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"adultSeat\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"childSeat\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"specialSeat\");\r\n");
      out.write("\t\t$result.html(\"\");\r\n");
      out.write("\t\tresult=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentVal == 0){\r\n");
      out.write("\t\talert(\"최소 1명 이상의 인원을 선택하세요.\");\r\n");
      out.write("\t\t$(\"#adult_counter\").html(0);\r\n");
      out.write("\t\t$(\"#child_counter\").html(0);\r\n");
      out.write("\t\t$(\"#special_counter\").html(0);\r\n");
      out.write("\t\t//가격\r\n");
      out.write("\t\t$(\"#total\").html(0);\r\n");
      out.write("\t\ttotalPrice = 0;\r\n");
      out.write("\t\t//좌석\r\n");
      out.write("\t\t$(\".seat li\").not($(\".Y, .disabledSeat\")).css(\"background\", \"gray\");\r\n");
      out.write("\t\t$(\".disabledSeat\").not($(\".Y\")).css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"clicked\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"adultSeat\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"childSeat\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"specialSeat\");\r\n");
      out.write("\t\t$result.html(\"\");\r\n");
      out.write("\t\tresult=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(currentVal > 8){\r\n");
      out.write("\t\talert(\"인원 선택은 최대 8명까지 가능합니다.\");\r\n");
      out.write("\t\t$(\".sort\").val(0);\r\n");
      out.write("\t\t$(\"#adult_counter\").html(0);\r\n");
      out.write("\t\t$(\"#child_counter\").html(0);\r\n");
      out.write("\t\t$(\"#special_counter\").html(0);\r\n");
      out.write("\t\t//가격\r\n");
      out.write("\t\t$(\"#total\").html(0);\r\n");
      out.write("\t\ttotalPrice = 0;\r\n");
      out.write("\t\t//좌석\r\n");
      out.write("\t\t$(\".seat li\").not($(\".Y, .disabledSeat\")).css(\"background\", \"gray\");\r\n");
      out.write("\t\t$(\".disabledSeat\").not($(\".Y\")).css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"clicked\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"adultSeat\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"childSeat\");\r\n");
      out.write("\t\t$(\".seat li\").removeClass(\"specialSeat\");\r\n");
      out.write("\t\t$result.html(\"\");\r\n");
      out.write("\t\tresult=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("/* 2. 좌석 선택 */\r\n");
      out.write("$seat.on('click', 'li', function() {\r\n");
      out.write("var $this = $(this),\r\n");
      out.write("    index = $this.index();\r\n");
      out.write("\t\t//선택 좌석\r\n");
      out.write("\t\t\tif(currentVal<9 && $this.hasClass(\"clicked\") === false && $(\".clicked\").length < currentVal){\r\n");
      out.write("\t\t\t\t//장애인석일 경우\r\n");
      out.write("\t\t\t\tif($this.hasClass(\"disabledSeat\") === true){\r\n");
      out.write("\t\t\t\t\talert(\"장애인석을 선택하셨습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t$(this).addClass(\"clicked\");\r\n");
      out.write("\t\t\t$this.css(\"background\", \"rgb(53, 37, 107)\");\r\n");
      out.write("\t\t\tresult += \"<p class='getResult'>\"+getSeatName(index)+\" \"+\"</p>\";\r\n");
      out.write("\t  \t\t$result.html(result);\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//인원 입력\r\n");
      out.write("\t\t//성인이 0이 아닐 때\r\n");
      out.write("\t\tif(currentVal<9 && adultVal != 0 && $(\".adultSeat\").length < adultVal){\r\n");
      out.write("\t\t\t$this.addClass(\"adultSeat\");\r\n");
      out.write("\t\t\t$(\"#adult_counter\").html($(\".adultSeat\").length);\r\n");
      out.write("\t\t\ttotalPrice += adultPrice;\r\n");
      out.write("\t\t\t$(\"#total\").html(totalPrice);\r\n");
      out.write("\t\t\t//console.log(totalPrice);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t \tif(currentVal<9 && adultVal == $(\".adultSeat\").length && $(this).attr('class') == 'clicked'){\r\n");
      out.write("\t\t\tif(childVal != 0 && $(\".childSeat\").length < childVal){\r\n");
      out.write("\t\t\t\t$this.addClass(\"childSeat\");\r\n");
      out.write("\t\t\t\t$(\"#child_counter\").html($(\".childSeat\").length);\r\n");
      out.write("\t\t\t\ttotalPrice += childPrice;\r\n");
      out.write("\t\t\t\t$(\"#total\").html(totalPrice);\r\n");
      out.write("\t\t\t\t//console.log(totalPrice);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t \tif(currentVal<9 && childVal == $(\".childSeat\").length && $(this).attr('class') == 'clicked'){\r\n");
      out.write("\t \t\tif(specialVal != 0 && $(\".specialSeat\").length < specialVal){\r\n");
      out.write("\t\t\t\t$this.addClass(\"specialSeat\");\r\n");
      out.write("\t\t\t\t$(\"#special_counter\").html($(\".specialSeat\").length);\r\n");
      out.write("\t\t\t\ttotalPrice += specialPrice;\r\n");
      out.write("\t\t\t\t$(\"#total\").html(totalPrice);\r\n");
      out.write("\t\t\t\t//console.log(totalPrice);\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t}\r\n");
      out.write("}); //seat.on - click 끝\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var updateView = function() {\r\n");
      out.write("    var makeTag = '', i = 1, leng = 0;\r\n");
      out.write("\r\n");
      out.write("    colsNum = ");
      out.print(colsNum);
      out.write(";\r\n");
      out.write("    rowsNum = ");
      out.print(rowsNum);
      out.write(";\r\n");
      out.write("\t\r\n");
      out.write("    var a = 64;\r\n");
      out.write("    var b = 64;\r\n");
      out.write("    for(i = 1, leng = colsNum * rowsNum; i <= leng; i++) {\r\n");
      out.write("        if( i % colsNum === 1 ) {\r\n");
      out.write("\t        a++;\r\n");
      out.write("\t        b++;\r\n");
      out.write("            makeTag += \"<li style='clear:both;' name=\"+i+\" id=\"+String.fromCharCode(a)+1+\">\"+1+\"</li>\";\r\n");
      out.write("            var j = 1;\r\n");
      out.write("        } else{\r\n");
      out.write("            j++;\r\n");
      out.write("            makeTag += \"<li name=\"+j+\" id=\"+String.fromCharCode(b)+j+\">\"+j+\"</li>\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    $seat.html(makeTag);\r\n");
      out.write("    \r\n");
      out.write("    if(rowsNum == 7 && colsNum == 12){\r\n");
      out.write("\t    $(\"li[name='7']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("\t    $(\"li[name='11']\").first().css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("\t    $(\"li[name='12']\").first().css(\"background\", \"rgb(70, 137, 98)\");\r\n");
      out.write("\t    $(\"li[name='12']\").last().css(\"display\", \"none\");    \t\r\n");
      out.write("    }\r\n");
      out.write("    if(rowsNum == 6 && colsNum == 11){\r\n");
      out.write("    \t$(\"li[name='3']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("    \t$(\"li[name='10']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("    }\r\n");
      out.write("    if(rowsNum == 7 && colsNum == 11){\r\n");
      out.write("    \t$(\"li[name='5']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("    \t$(\"li[name='10']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("    \t$(\"li[name='10']\").last().css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='11']\").last().css(\"display\", \"none\");\r\n");
      out.write("    }\r\n");
      out.write("    if(rowsNum == 8 && colsNum == 11){\r\n");
      out.write("    \t$(\"li[name='3']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='4']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='5']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='6']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='7']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='8']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='9']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='10']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='11']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='12']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("    \t$(\"li[name='3']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("    \t$(\"li[name='8']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("    \t$(\"li[name='4']\").eq(3).css(\"margin-right\", \"194px\");\r\n");
      out.write("    }\r\n");
      out.write("    if(rowsNum == 6 && colsNum == 12){\r\n");
      out.write("    \t$(\"li[name='7']\").css(\"margin-left\", \"50px\");\r\n");
      out.write("    \t\r\n");
      out.write("\t\t$(\"li[name='12']\").eq(3).css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\"li[name='12']\").eq(4).css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\"li[name='12']\").eq(5).css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\"li[name='11']\").eq(4).css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\"li[name='11']\").eq(5).css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\"li[name='10']\").eq(5).css(\"display\", \"none\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    for(makeTag = '', i = 1, leng = colsNum; i <= leng; i++) {\r\n");
      out.write("        makeTag += '<li>' + i + '</li>';\r\n");
      out.write("    }\r\n");
      out.write("    $colsHead.html(makeTag);\r\n");
      out.write("\r\n");
      out.write("    for(makeTag = '', i = 65, leng = 65 + rowsNum; i < leng; i++) {\r\n");
      out.write("        makeTag += '<li>' + String.fromCharCode(i) + '</li>';\r\n");
      out.write("    }\r\n");
      out.write("    $rowsHead.html(makeTag);\r\n");
      out.write("    \r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var getSeatName = function( index ) {\r\n");
      out.write("    var colsIndex = (index % colsNum) + 1,\r\n");
      out.write("        rowsIndex = Math.ceil((index + 1) / colsNum) - 1,\r\n");
      out.write("        rowsName = String.fromCharCode((65 + rowsIndex));\r\n");
      out.write("\r\n");
      out.write("    return rowsName+colsIndex;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("$('fieldset').on('input', 'input', function() {\r\n");
      out.write("    updateView();\r\n");
      out.write("    return false;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("updateView();\r\n");
      out.write("\r\n");
      out.write("<!-- @수정@ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\"> -->\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!-- 풋터 -->\n");
      out.write("<footer class=\"foot\">\n");
      out.write("    <div id=bottomFoot class=\"bottom_foot\">\n");
      out.write("        <ul class=\"div-bottomfoot\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">공지사항\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">고객센터\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이용약관\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이벤트\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">스토어바로가기\n");
      out.write("            </li>\n");
      out.write("        </ul>           \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- 풋터 안 인포메이션 -->\n");
      out.write("    <div id=\"infoFoot\" class=\"info_foot\">\n");
      out.write("                                \n");
      out.write("        <span>사업자정보확인</span> <span>개인정보관리자</span><span>통신판매 신고번호 제 00000123123호</span> <br><br>\n");
      out.write("        <span>대표이사: NONAME</span> <span>본점: 서울특별시 서초구 서초동 123-456</span> <span>사업장: 서울특별시 마포구 상암로 123 상암동 456</span><br><br>\n");
      out.write("        <span>고객센터: 1234-5678</span> <span>NOTITLE문의: 02-1234-5678</span> <span>NOTITLE문의:  csnotitle@notitle.com</span>\n");
      out.write("        \n");
      out.write("    <h3>PIXARBOX</h3>\n");
      out.write("    </div><!-- div.info_foot div-->\n");
      out.write("\n");
      out.write("    <div class=\"end_foot\">\n");
      out.write("        InsideOut\n");
      out.write("    </div><!--div.end_foot-->\n");
      out.write("    <!-- 풋터 안 인포메이션 끝 -->\n");
      out.write("</footer>\n");
      out.write("    <!-- 풋터 끝 -->   \n");
      out.write("            \n");
      out.write("            \n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
