/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-06 03:04:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.movie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class boxOffice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1578022508000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577923558000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	int totalPage = (int)request.getAttribute("totalPage");
	//System.out.println(totalPage);
	
	int order = (int)request.getAttribute("order");
	//System.out.println("order="+order);

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');

	//로그인한 경우
	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	//System.out.println("memberLoggedIn@header.jsp="+memberLoggedIn);

	//쿠키관련
	boolean saveId = false;
	String loginId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null) {
		for(Cookie c : cookies) {
			String k = c.getName();
			String v = c.getValue();
			
			if("saveId".equals(k)) {
				saveId = true;
				loginId = v;
			}
		}
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>PIXARBOX</title>\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("<!--웹폰트추가  -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Anton|Do+Hyeon|Nanum+Gothic+Coding&display=swap&subset=latin-ext,vietnamese\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script> -->\n");
      out.write("\n");
      out.write("<!--슬라이드코드추가--> \n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 파비콘추가-->\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 헤더  -->\n");
      out.write("<header id=\"header\" class=\"header_main\">\n");
      out.write("\n");
      out.write("<!-- 두번째 헤더 -->\n");
      out.write("    <div class=\"sec_haed\">\n");
      out.write("\t    <!-- 고정헤더 -->\n");
      out.write("\t    <nav id=\"topUtil\" class=\"top_util\">\n");
      out.write("\t        <span>PIXAR</span>\n");
      out.write("\t        <ul class=\"nav\">\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 if(memberLoggedIn == null) { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogin\" id=\"login_btn\">로그인</a>        \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=\"sign_btn\">회원가입</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t        ");
      out.write("\n");
      out.write("\t        ");
 }
	        else if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())) { 
	        
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t        \t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\" id=\"admin_btn\">관리자페이지</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a></li>\n");
      out.write("\t        ");
 }
	        else { 
      out.write("\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" id=\"home\">홈</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberLogout\" id=\"sign_out_btn\">로그아웃</a>   \n");
      out.write("\t\n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/my/mypage.do?memberId=");
      out.print(memberLoggedIn.getMemberId() );
      out.write("\" id=\"mypage_btn\">마이페이지</a>   \n");
      out.write("\t            </li>\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/notice/notice.do\" id=\"customer_btn\">고객센터</a>\n");
      out.write("\t            </li>\n");
      out.write("\t    ");
 } 
      out.write("\n");
      out.write("\t        </ul>\n");
      out.write("\t    </nav>\n");
      out.write("\t<!-- 고정헤더 끝 -->\n");
      out.write("        <nav id=\"secUtil\" class=\"sec_util\">\n");
      out.write("            \n");
      out.write("            <span>\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath() );
      out.write("\">PIXAR<br><br>BOX</a>\n");
      out.write("            </span>\n");
      out.write("                \n");
      out.write("            <ul class=\"nav-sec\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/ticket/ticketingStep1/step1.do\">예매</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/movie/boxOffice/order1.do\">영화</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/theater/theaterInfo\">영화관</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">이벤트</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">스토어</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">VOD</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </div><!--div.sec_haed-->\n");
      out.write("    <!-- 두번째 헤더 끝 -->\n");
      out.write("</header>\n");
      out.write("<!-- 헤더 끝 -->\n");
      out.write("\n");
      out.write("<!-- <section id=\"content\"> -->\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/movie_boxOffice.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- 해야 할 것 \r\n");
      out.write("- 박스오피스, 예매순 글자 보라색\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"content-boxOffice\">\r\n");
      out.write("\t<div id=\"menuLine\">\r\n");
      out.write("           <ul id=\"movieMenu\">\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/movie/boxOffice/order1.do\" id=\"orderTicketing\">박스오피스</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/movie/movieNow/movieNow.do\" id=\"m2\">현재상영작</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/movie/scheduleMovie/scheduleMovie.do\" id=\"m3\">상영예정작</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/movie/find/movieFinder.do\" id=\"m4\">영화찾기</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"orderMenu-wrap\">\r\n");
      out.write("          <ul id=\"orderMenu\">\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/movie/boxOffice/order1.do\" id=\"orderByTicketing\">예매순</a></li>\r\n");
      out.write("              <span style=\"color:gray;\">&nbsp;|&nbsp;</span>\r\n");
      out.write("              <li id=\"order_2\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/movie/boxOffice/order2.do\" id=\"orderByYear\">개봉일순</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      ");

		if (memberLoggedIn != null) {
			if (memberLoggedIn.getMemberId().equals("admin")) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"add\">\r\n");
      out.write("\t\t<button id=\"add-movie\" onclick=\"addMovieFunc();\">영화 추가</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");

			}
		}
	
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <!-- ul 반복문  // mardin전체 div로 주기-->\r\n");
      out.write("      <div id=\"movieList\">\r\n");
      out.write("     \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"btn-more-container\">\r\n");
      out.write("\t  \t<button id=\"btn-more\" value=\"1\">더보기(1/");
      out.print(totalPage );
      out.write(")</button>\r\n");
      out.write("\t  </div>\r\n");
      out.write("     \r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 이전에 사용한 CSS를 브라우저가 캐쉬에 보관해놓고 사용하기에\r\n");
      out.write("링크된 CSS 변화점을 기억하지 못하는 것이라고 함 아무의미 없는 ?alter로 써줌-->\r\n");
      out.write("\r\n");
      out.write("<!-- 해야 할 것 \r\n");
      out.write("- 박스오피스, 예매순 글자 보라색\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var num = 1;\r\n");
      out.write("\r\n");
      out.write("function ticketing(){\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath() );
      out.write("/ticket/ticketingStep1/step1.do\";\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(()=>{\r\n");
      out.write("\tmorePage(1);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btn-more\").click(e=>{\r\n");
      out.write("\t\tmorePage($(e.target).val());\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//DAO 상에서 이미 좋아요가 눌러진 영화인지 판별한 후에\r\n");
      out.write("//추가 해줄지 말지 여부 판단하기.\r\n");
      out.write("function likeFunc(m){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//로그인 안했을 때 조건문 달아주기\r\n");
      out.write("\t");
if(memberLoggedIn != null){
		if(!"admin".equals(memberLoggedIn.getMemberId())){
      out.write("\r\n");
      out.write("\t\tvar params = {\r\n");
      out.write("\t\t\t\tmovieCode: m,\r\n");
      out.write("\t\t\t\tmemberId:  '");
      out.print(memberLoggedIn.getMemberId());
      out.write("'\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/movie/movieLike\",\r\n");
      out.write("\t\t\tdata: params,\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: data => {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//console.log(data);\r\n");
      out.write("\t\t\t\t//0or1로 데이터가 넘어온다.\r\n");
      out.write("\t\t\t\t//1일때는 insert가 되었을때\r\n");
      out.write("\t\r\n");
      out.write("\t\t \t\tfor(let i in data){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tlet p = data[i];\r\n");
      out.write("\t\t\t\t\tif(p.clickResult==1){\r\n");
      out.write("\t\t\t\t\t\t//console.log(\"1\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+m).removeClass(\"notHeart\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+m).addClass(\"heart\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\talert(\"해당영화가 찜 목록에 추가되었습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(p.clickResult==0){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+m).removeClass(\"heart\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+m).addClass(\"notHeart\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\talert(\"해당영화가 찜 목록에 삭제되었습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: (x,s,e) =>{\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패!\", x, s, e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      } 
		}
	else{ 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\talert(\"로그인후 이용하세요.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//order가 1이면 ticket순 2면 year순\r\n");
      out.write("\tvar orderVal = ");
      out.print(order);
      out.write(";\r\n");
      out.write("\r\n");
      out.write("\t\tfunction morePage(cPage){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 if(memberLoggedIn != null){
      out.write("\r\n");
      out.write("\t\t\t\tvar param = {\r\n");
      out.write("\t\t\t\t\t\tcPage: cPage,\t\t\r\n");
      out.write("\t\t\t\t\t\tmemberId:  '");
      out.print(memberLoggedIn.getMemberId());
      out.write("',\r\n");
      out.write("\t\t\t\t\t\torderVal: orderVal\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar param = {\r\n");
      out.write("\t\t\t\t\t\tcPage: cPage,\r\n");
      out.write("\t\t\t\t\t\tmemberId:  \"null\",\r\n");
      out.write("\t\t\t\t\t\torderVal: orderVal\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/movie/movieMore\",\r\n");
      out.write("\t\t\t\t\tdata: param,\r\n");
      out.write("\t\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess: data => {\r\n");
      out.write("\t\t\t\t\t\t//console.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	int cnt = 0;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfor(let i  in data) {\r\n");
      out.write("\t\t\t\t\t\t\t");
 cnt = 0;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tlet html = \"\";\r\n");
      out.write("\t\t\t\t\t\t\tlet p = data[i];\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<div class='moviePoster'>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<div class='ranking_box'>\"+num+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<a href='\"+\"");
      out.print(request.getContextPath() );
      out.write("/movie/movieView/movieDescription.do?movieCode=\"+p.movieCode+\"&memberId=");
      out.print(memberLoggedIn!=null?memberLoggedIn.getMemberId():"");
      out.write("'><img src='");
      out.print(request.getContextPath() );
      out.write("/images/\"+p.movieImg+\"' class='poster'></a>\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar mc = p.movieCode;\r\n");
      out.write("\t\t\t\t\t\t\t//console.log(p.like);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(p.like==1){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<img class='heart' id='\"+mc+\"' src='");
      out.print(request.getContextPath() );
      out.write("/images/hearts.png'>\"\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<img class='notHeart' id='\"+mc+\"' src='");
      out.print(request.getContextPath() );
      out.write("/images/hearts.png'>\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<div class='title'>\"+p.movieTitle+\"</div>\"\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<div class='date'>개봉일 <span>\"+p.releaseDate+\"</span></div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(memberLoggedIn!=null){
								if(!memberLoggedIn.getMemberId().equals("admin")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += \"<button class='like' onclick='likeFunc(\\\"\"+p.movieCode+\"\\\")';>찜하기</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += \"<button class='ticketing' onclick='ticketing();'>예매하기</button>\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 }   
							}else if(memberLoggedIn==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += \"<button class='like' onclick='likeFunc(\\\"\"+p.movieCode+\"\\\")';>찜하기</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml += \"<button class='ticketing' onclick='ticketing();'>예매하기</button>\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#movieList\").append(html);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t       num++;\r\n");
      out.write("\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//더보기버튼 작업\r\n");
      out.write("\t\t\t\t\t$(\"#btn-more\").val(Number(cPage)+1)\r\n");
      out.write("\t\t\t\t\t\t\t\t  .text(\"더보기(\"+cPage+\"/");
      out.print(totalPage);
      out.write(")\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t//마지막페이지\r\n");
      out.write("\t\t\t\t\tif(cPage == ");
      out.print(totalPage);
      out.write(")\r\n");
      out.write("\t\t\t\t\t\t$(\"#btn-more\").attr(\"disabled\",\"disabled\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  .css(\"cursor\", \"not-allowed\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: (x,s,e) =>{\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리실패!\", x, s, e);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function addMovieFunc(){\r\n");
      out.write("\t\r\n");
      out.write("\talert(\"영화를 추가해 봅시다.\");\r\n");
      out.write("\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/admin/addMovie\";\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(()=> {\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(()=> {\r\n");
      out.write("\tif(");
      out.print(order);
      out.write("==1) {\r\n");
      out.write("\t\t$(\"#orderByTicketing\").css(\"color\", \"#503396\");\r\n");
      out.write("\t\t//console.log(");
      out.print(order);
      out.write(");\r\n");
      out.write("\t\t//console.log($(\"#orderTicketing\"));\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(");
      out.print(order);
      out.write("==2)\r\n");
      out.write("\t\t$(\"#orderByYear\").css(\"color\", \"#503396\");\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- slick -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("<!-- icon -->\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\n");
      out.write("<!-- bx slider -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.   css\"> -->\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("\n");
      out.write("<!-- script slick, bxslider -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://kenwheeler.github.io/slick/slick/slick.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("<!-- 풋터 -->\n");
      out.write("<footer class=\"foot\">\n");
      out.write("    <div id=bottomFoot class=\"bottom_foot\">\n");
      out.write("        <ul class=\"div-bottomfoot\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">공지사항\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">고객센터\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이용약관\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">이벤트\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">스토어바로가기\n");
      out.write("            </li>\n");
      out.write("        </ul>           \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- 풋터 안 인포메이션 -->\n");
      out.write("    <div id=\"infoFoot\" class=\"info_foot\">\n");
      out.write("                                \n");
      out.write("        <span>사업자정보확인</span> <span>개인정보관리자</span><span>통신판매 신고번호 제 00000123123호</span> <br><br>\n");
      out.write("        <span>대표이사: NONAME</span> <span>본점: 서울특별시 서초구 서초동 123-456</span> <span>사업장: 서울특별시 마포구 상암로 123 상암동 456</span><br><br>\n");
      out.write("        <span>고객센터: 1234-5678</span> <span>NOTITLE문의: 02-1234-5678</span> <span>NOTITLE문의:  csnotitle@notitle.com</span>\n");
      out.write("        \n");
      out.write("    <h3>PIXARBOX</h3>\n");
      out.write("    </div><!-- div.info_foot div-->\n");
      out.write("\n");
      out.write("    <div class=\"end_foot\">\n");
      out.write("        InsideOut\n");
      out.write("    </div><!--div.end_foot-->\n");
      out.write("    <!-- 풋터 안 인포메이션 끝 -->\n");
      out.write("</footer>\n");
      out.write("    <!-- 풋터 끝 -->   \n");
      out.write("            \n");
      out.write("            \n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
